apiVersion: apps/v1
kind: Deployment
metadata: 
  name: task-management
  labels:
    app: task-management
    tier: task-management
spec:
  replicas: 1
  selector:
    matchLabels:  
      app: task-management
  template:
    metadata: 
      labels:
        app: task-management
    spec: 
      containers:
        - name: taskmanagement
          image: aleksandragjoreska/taskmanagement
          ports:
            - containerPort: 3000
          env:
            - name: MONGO_URI
              valueFrom:
                 secretKeyRef:
                  name: mongo-secret
                  key: MONGO_URI
      restartPolicy: Always