name: docker-build-and-push
on:
  push:
    branches:
      - 'master'
jobs:
  build-node:
    runs-on: ubuntu-latest
    container: node:16
    steps:
      - run: node --version
      - run: npm --version
      - uses: actions/checkout@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - run: npm install
      - run: npm start
      - run: docker build -t aleksandragjoreska/taskmanagement
      - run: docker push aleksandragjoreska/taskmanagement